import { Platform } from 'react-native';

export async function transcribeAudio(audioUri: string, audioBlob?: Blob): Promise<string> {
    const SARVAM_API_KEY = process.env.EXPO_PUBLIC_SARVAM_API_KEY || process.env.SARVAM_API_KEY;

    if (!SARVAM_API_KEY) {
        throw new Error("Sarvam API Key is missing. Set SARVAM_API_KEY in .env");
    }

    if (!audioUri && !audioBlob) {
        throw new Error("Audio URI or Blob is required for transcription.");
    }

    const formData = new FormData();

    if (Platform.OS === 'web') {
        const blob = audioBlob || await fetch(audioUri).then(r => r.blob());
        formData.append('file', blob as any, 'recording.webm');
    } else {
        // Automatically grab the correct extension generated by expo-av (usually .m4a)
        const fileExt = audioUri.split('.').pop() || 'm4a';
        formData.append('file', {
            uri: audioUri,
            name: `recording.${fileExt}`,
            type: `audio/${fileExt}`,
        } as any);
    }

    formData.append('model', 'saaras:v3');

    try {
        const response = await fetch("https://api.sarvam.ai/speech-to-text", {
            method: "POST",
            headers: {
                "api-subscription-key": SARVAM_API_KEY,
            },
            body: formData,
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`STT API error (${response.status}): ${errorText}`);
        }

        const data = await response.json();

        if (data.transcript) {
            return data.transcript;
        } else {
            throw new Error("No transcript payload returned from Sarvam STT API.");
        }
    } catch (error: any) {
        console.error("Audio transcription failed:", error);
        throw new Error(error.message || "Failed to transcribe audio.");
    }
}